In [1]:
!pip install numpy


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
!python.exe -m pip install --upgrade pip

   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 1.8/1.8 MB 9.5 MB/s  0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 25.3
    Uninstalling pip-25.3:
      Successfully uninstalled pip-25.3


In [ ]:
# 1d array
import numpy as np
arr1=np.array([1,2,3,10,4,5,6])
print(arr1)
print(type(arr1))
print(arr1.shape)

[ 1  2  3 10  4  5  6]
<class 'numpy.ndarray'>
(7,)


In [ ]:
#2d array
arr2 = np.array([[1,2,3,45],[2,4,56,6]])
print(arr2)
print(arr2.shape)

[[ 1  2  3 45]
 [ 2  4 56  6]]
(2, 4)


In [11]:
np.arange(0,10,2).reshape(5,1)


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
arr= np.array([[1,2,3],[6,7,8]])

print("array\n",arr)
print("shape\n",arr.shape)
print("number of dimension:",arr.ndim)
print("size(no.of elements):",arr.size)
print("data type:",arr.dtype)
print("item size (in bytes):",arr.itemsize)

array
 [[1 2 3]
 [6 7 8]]
shape
 (2, 3)
number of dimension: 2
size(no.of elements): 6
data type: int64
item size (in bytes): 8


In [15]:
## numpy vectorized operation

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])
print("addition:",arr1+arr2)
print("subtraction:",arr1-arr2)
print("multiplication:",arr1*arr2)
print("division:", arr1/arr2)



addition: [11 22 33 44 55]
subtraction: [ -9 -18 -27 -36 -45]
multiplication: [ 10  40  90 160 250]
division: [0.1 0.1 0.1 0.1 0.1]


In [ ]:
### Universal function 

arr = np.array([2,3,4,6])
print(np.sqrt(arr))
#exponential
print(np.sin(arr))
#sine
print(np.sin(arr))
#natural log
print(np.log(arr))


[1.41421356 1.73205081 2.         2.44948974]
[ 0.90929743  0.14112001 -0.7568025  -0.2794155 ]
[ 0.90929743  0.14112001 -0.7568025  -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.79175947]


In [18]:
## array slicing and indexing

arr = np.array([[1,2,3,4],[5,6,78,4],[12,23,45,67]])

print(arr)

[[ 1  2  3  4]
 [ 5  6 78  4]
 [12 23 45 67]]


In [24]:
arr[0][1]
print(arr[0:2])

[[ 1  2  3  4]
 [ 5  6 78  4]]


In [26]:
print(arr[1:,1:3])

[[ 6 78]
 [23 45]]


In [22]:
arr[2:]

array([[12, 23, 45, 67]])

In [25]:
arr[1:2,2:]

array([[78,  4]])

In [27]:
#modification

arr[0,0]= 101
print(arr)

[[101   2   3   4]
 [  5   6  78   4]
 [ 12  23  45  67]]


In [28]:
arr[1:]=100
print(arr)

[[101   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [29]:
data = np.array([1,2,3,4,5])
mean = np.mean(data)
std_dev= np.std(data)

normalized_data=(data-mean)/std_dev
print("normalized data:",normalized_data)

normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [30]:
data = np.array([1,2,12,22,34,5,6,7,8,910])

mean= np.mean(data)
print("mean:", mean)

median= np.median(data)
print("median", median)

std_dev = np.std(data)
print("std_dev",std_dev)

variance=np.var(data)
print("variance",variance)

mean: 100.7
median 7.5
std_dev 269.9366777598035
variance 72865.80999999998


In [48]:
# logical operation
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>=5)| (data<=4)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])